import type { Metadata } from "next";
import "@/styles/style.scss";
import UserNavbar from "@/components/navbars/user-navbar/UserNavbar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <UserNavbar />
                {children}
            </body>
        </html>
    );
}
